### ISSUE TITLE
Some problems with blur

### ISSUE THREAD

**Issue by ghost** [DelusionalLogic/compton#4]
First off, I have to congratulate you as this fork gets rid of most of the sluggishness and stuttering I experienced on compton. I noticed some problems witht he blurring features, though. The "blur-background-fixed" option does not work, which makes the transition as a blurred window is faded out rather jarring. Aside from that, I had some problems setting a blur kernel and couldn't figure out how to change it to something else. I'm on version git-v0.1_beta2-94-gedcc876-2018-05-31 on Void Linux with an Nvidia 1080ti and driver version 396.24.02 if that helps

**Comment by DelusionalLogic** [comment]
Currently I'm still in the process of cleaning up the code. I'd regard this project as early to mid Alpha.

If i recall, `blur-background-fixed` adjusts the blur as the window fades in/out, that's unfortunately not possible with the new blur method. I'll be implementing fading blur (with opacity) once I've gotten everything stable.

Customizable Blur Kernels have been removed in favor of a down/up sampling based blur method similar to the one recently adopted by KDE. You will be able to change the up/downsample shaders.

You might see that most development is going on in the `develop-gl3.2` branch.

What were you using the custom blur kernels for? I'm interested in hearing usecases.

**Comment by ghost** [comment]
I guess I don't really need custom kernels.  I just like 15x15 gaussian blur, which can't be used by name in compton, meaning you have to include the whole kernel in your config. Your system definitely sounds a lot more user friendly and I'm happy to wait for stability.

**Comment by DelusionalLogic** [comment]
Nice big blur kernels is what I want too.

Just don't expect stability to arrive soon, cleaning up Compton is going to require a lot of work.
